-- 코드를 입력하세요
SELECT C.AUTHOR_ID, C.AUTHOR_NAME, CATEGORY, SUM(PRICE * SALES) AS "TOTAL_SALES"
FROM BOOK_SALES A
JOIN BOOK B
ON A.BOOK_ID = B.BOOK_ID
JOIN AUTHOR C
ON B.AUTHOR_ID = C.AUTHOR_ID
WHERE TO_CHAR(SALES_DATE,'YYYYMM') = '202201'
GROUP BY C.AUTHOR_ID, C.AUTHOR_NAME, CATEGORY
ORDER BY AUTHOR_ID, CATEGORY DESC