SELECT * FROM (
SELECT A.CAR_ID, A.CAR_TYPE, A.DAILY_FEE * 0.3 * (100 - NVL((SELECT DISCOUNT_RATE FROM CAR_RENTAL_COMPANY_DISCOUNT_PLAN WHERE CAR_TYPE = A.CAR_TYPE AND REGEXP_SUBSTR(DURATION_TYPE, '[0-9]+') = '30' ),0))  AS "FEE"
FROM CAR_RENTAL_COMPANY_CAR A
WHERE CAR_TYPE IN ('세단','SUV')
  AND NOT EXISTS (
    SELECT 1 
    FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY
    WHERE CAR_ID = A.CAR_ID
      AND TO_CHAR(START_DATE,'YYYYMMDD') <= '20221130'
      AND TO_CHAR(END_DATE,'YYYYMMDD') >= '20221101'
  )
)
WHERE FEE BETWEEN 500000 AND 2000000
ORDER BY FEE DESC, CAR_TYPE, CAR_ID DESC