-- 코드를 입력하세요
SELECT YEAR,TO_NUMBER(MONTH),COUNT(DISTINCT USER_ID) AS "PURCHASED_USERS",
    ROUND(COUNT(DISTINCT USER_ID) / 
    (SELECT COUNT(DISTINCT USER_ID)
    FROM USER_INFO
    WHERE TO_CHAR(JOINED,'YYYY') = '2021'),1) AS "PUCHASED_RATIO"
FROM (
SELECT ONLINE_SALE_ID, USER_ID, 
    TO_CHAR(SALES_DATE,'YYYY') AS "YEAR",
    TO_CHAR(SALES_DATE,'MM') AS "MONTH"
FROM ONLINE_SALE
WHERE USER_ID IN (
    SELECT DISTINCT USER_ID
    FROM USER_INFO
    WHERE TO_CHAR(JOINED,'YYYY') = '2021'
))
GROUP BY YEAR, MONTH
ORDER BY YEAR, MONTH