-- 코드를 입력하세요
SELECT DISTINCT A.CAR_ID, CASE WHEN B.CAR_ID IS NULL THEN '대여 가능' ELSE '대여중' END AS "AVAILABILITY"
FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY A
LEFT JOIN (
    SELECT DISTINCT CAR_ID 
    FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY
    WHERE TO_DATE('20221016','YYYY-MM-DD') BETWEEN START_DATE AND END_DATE
) B
ON A.CAR_ID = B.CAR_ID
ORDER BY A.CAR_ID DESC
