-- 코드를 입력하세요
SELECT * FROM (
SELECT A.HISTORY_ID, (END_DATE - START_DATE + 1) * DAILY_FEE * 
(100 - NVL((SELECT MAX(DISCOUNT_RATE) FROM CAR_RENTAL_COMPANY_DISCOUNT_PLAN WHERE CAR_TYPE = '트럭' AND REGEXP_SUBSTR(DURATION_TYPE, '[0-9]+') <= (END_DATE - START_DATE + 1)),0)) / 100 AS "FEE"
FROM
CAR_RENTAL_COMPANY_RENTAL_HISTORY A
JOIN CAR_RENTAL_COMPANY_CAR B
ON A.CAR_ID = B.CAR_ID
WHERE CAR_TYPE = '트럭'
)
ORDER BY FEE DESC, HISTORY_ID DESC

