-- 코드를 입력하세요
SELECT * FROM (
SELECT A.FLAVOR
FROM FIRST_HALF A
JOIN (
    SELECT FLAVOR, SUM(TOTAL_ORDER) AS "TOT"
    FROM JULY
    GROUP BY FLAVOR
) B
ON A.FLAVOR = B.FLAVOR
GROUP BY A.FLAVOR
ORDER BY SUM(A.TOTAL_ORDER + B.TOT) DESC
)
WHERE ROWNUM <= '3'