-- 코드를 입력하세요
SELECT B.NUM, COUNT(A.ANIMAL_ID)
FROM (SELECT LEVEL - 1 AS NUM
      FROM DUAL
      CONNECT BY LEVEL <= 24) B
LEFT JOIN ANIMAL_OUTS A
ON TO_CHAR(DATETIME,'HH24') = B.NUM
GROUP BY B.NUM
ORDER BY B.NUM