-- 코드를 입력하세요
SELECT NUM,COUNT(A.ANIMAL_ID)
FROM ANIMAL_OUTS A
JOIN (
    SELECT 8 + LEVEL AS NUM
    FROM DUAL
    CONNECT BY LEVEL <= 11
) B 
ON TO_NUMBER(TO_CHAR(A.DATETIME,'HH24')) = B.NUM
GROUP BY NUM
ORDER BY NUM