-- 코드를 입력하세요
SELECT MCDP_CD AS "진료과코드", NUM AS "5월예약건수"
FROM (
SELECT MCDP_CD, COUNT(APNT_NO) AS NUM
FROM APPOINTMENT
WHERE TO_CHAR(APNT_YMD,'YYYYMM') = '202205'
GROUP BY MCDP_CD
)
ORDER BY NUM, MCDP_CD
