-- 코드를 입력하세요
SELECT A.CATEGORY, A.PRICE, PRODUCT_NAME
FROM FOOD_PRODUCT A
JOIN (
    SELECT CATEGORY, MAX(PRICE) AS "PRICE"
    FROM FOOD_PRODUCT 
    GROUP BY CATEGORY
) B
ON A.CATEGORY = B.CATEGORY
AND A.PRICE = B.PRICE
WHERE A.CATEGORY IN ('과자','김치','국','식용유')
ORDER BY A.PRICE DESC
